brycedrennan/imaginAIry

Dockerfile

gcc is required and not available from the docker image by default.

gcc is required

---

imaginairy/cmds.py

Thank you very much for this nice tool!
I've made a few improvements to the CLI help text, so that it is easier to know what the default values are and what kind of value is expected.  
Feel free to merge, or to close :-)
- Show all default values.
- Use more descriptive metavars, e.g., `TEXT` -> `PATH|URL`.
- Fix help texts to start with an uppercase letter and end with a dot.
- Use `click.Path()` and `float` types where necessary.
```
Options:
--prompt-strength FLOAT         How closely to follow the prompt. Image
looks unnatural at higher values  [default:
7.5]
--init-image TEXT               Starting image. filepath or url
--init-image-strength FLOAT     Starting image.  [default: 0.6]
--outdir TEXT                   where to write results to
-r, --repeats INTEGER           How many …
```

Improve CLI help text

---

imaginairy/schema.py

To improve reproducibility, I've added the negative prompts into the logs and EXIF metadata. The model was already placed into the Software field, but I thought it would be good to also include it into the JSON string. This will enable future deserialization from the EXIF data.
```
Generating 🖼  19/1000: "two young children (1 male) (1 female), with thick dark hair and light skin, blue eyes, making a plane with legos, comic book, marvel, superflat, dc comics, artistic rendering, alternate album cover, graphic novel, promotional art, deviantart contest winner, centered composition" 512x512px negative-prompt:"((((text)))), (logo), disfigured, fused fingers, extra limbs, realistic, photo, 3d render, 3 eyes, nsfw, grain, cropped, out of frame" seed:480030103 prompt-strength:7.5 steps:75 …
```

feat: include negative prompts in logs and EXIF metadata

---

.gitignore
imaginairy/cmds.py
imaginairy/configs/stable-diffusion-v1-inpaint.yaml
imaginairy/configs/stable-diffusion-v1.yaml
imaginairy/model_manager.py
imaginairy/modules/attention.py

A configuration `use_ema: False` was became necessary in the newer Stable Diffusion code but was missing from the 1.5 config.

fix: performance improvement. disable ema

---

imaginairy/model_manager.py

instead of (incorrectly) trying to detect the function signature of the old version, just catch the error and try the old signature

fix: hf_hub_download signature compat

---

imaginairy/model_manager.py

Creates empty folder so huggingface hub is happy.
https://github.com/huggingface/huggingface_hub/pull/1306

fix: bypass hf cache retrieval bug

---

imaginairy/model_manager.py

If a model has a remote filename with characters that might not be supported on the local cache filesystem, replace them during translation of URL to cached file path.
Closes #202.

Handle model paths with illegal characters in filename

---

imaginairy/enhancers/describe_image_blip.py
imaginairy/schema.py

Loading png images will cause the following error since PIL loads png images in RGBA mode.
```python
File "/Users/sunjiaming/miniconda3/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py", line 940, in normalize
return tensor.sub_(mean).div_(std)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0
```

fix: add png handling for LazyLoadingImage

---

.github/workflows/ci.yaml
README.md
imaginairy/__init__.py
imaginairy/api.py
imaginairy/bin/aimg
imaginairy/bin/imagine
imaginairy/cmds.py
imaginairy/config.py
imaginairy/debug_info.py
imaginairy/log_utils.py
imaginairy/safety.py
imaginairy/schema.py
imaginairy/version.py
setup.py
tests/test_config.py
tox.ini

just running `aimg --help` or `aimg --version` was very slow due to all the imports being brought in eagerly
Before changes `aimg --help`
`2.24s user 4.05s system 184% cpu 3.416 total`
After changes:
`0.04s user 0.02s system 8% cpu 0.625 total`
Used `PYTHONPROFILEIMPORTTIME=1 aimg --help` to find time consuming imports.
Also switched to using `scripts` instead of `entrypoints` since the scripts are much faster.
Made duplicate SAMPLER_TYPE_OPTIONS that can be loaded without loading all the samplers themselves.
Likely a breaking change - not sure.

perf: improve startup time by doing some imports lazily

---

README.md

In the multiline example with the "girl with the pearl earring" was a stray space. This led to following error:
```
...
"a modern female president" "a female robot" "a female doctor" "a female firefighter"
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
warnings.warn(
received 1 prompt(s) and will repeat them 1 times to create 1 images.
Generating 🖼  1/1: " " 512x512px negative-prompt:"Ugly, duplication, duplicates, mutilation, deformed, mutilated, mutation, twisted body, …
```

Removing stray space from readme at inopportune location

---

Makefile
README.md
setup.py

python converts entry_points to exe files so they run on windows.  The scripts that work on linux/macos don't work on windows.

fix: use entry_points for windows

---

imaginairy/schema.py

added `init-image-strength` and `model` so the complete set of metadata can be displayed and filtered on pnginfo inspectors or stable diffusion browsers such as https://breadboard.me

support additional metadata attributes

---

README.md
imaginairy/api.py
imaginairy/schema.py
imaginairy/utils.py

- fix: raw control images are now properly loaded. fixes #296
- fix: filenames start numbers after latest image, even if some previous images were deleted

fix raw control image processing

---

README.md

The command in the README:
```
imagine --control-image "image.png" --control-mode tile "sharp focus, high-resolution" --init-image-strength 0.2 --steps 30 -w 2048 -h 2048
```
generates the error:
```
Error: Invalid value for '--control-mode': 'tile' is not one of '', 'canny', 'depth', 'normal', 'hed', 'openpose'.
```
So I updated `tile` to `canny`

Fix incorrect command

---

README.md
imaginairy/config.py

Updates change log.
Removes deprecated features from README.
Removes deprecated model configs.

Update README.md for 14.0.0

---

imaginairy/api/generate.py
imaginairy/api/generate_refiners.py
imaginairy/cli/shared.py
imaginairy/config.py
imaginairy/enhancers/upscale_realesrgan.py
imaginairy/modules/refiners_sd.py
imaginairy/utils/log_utils.py
imaginairy/utils/memory_tracker.py
imaginairy/utils/model_manager.py
tests/test_utils/test_memory_tracker.py

fixes #424
- pref: improve memory usage when loading SD15.
- feature: clean up CLI output more
- feature: cuda memory tracking context manager
- feature: use safetensors fp16 for sd15

fix: interrupted generations don't prevent more generations

---

imaginairy/api/video_sample.py
imaginairy/cli/videogen.py
imaginairy/utils/animations.py

- allow generation at any size
- output "bounce" animations
- choose output format: mp4, webp, or gif
- fix random seed handling
- organize some code better

feature: videogen improvements

---

.github/workflows/ci.yaml
Makefile
tests/test_enhancers/test_clip_masking.py

waiting for this issue to be resolved before using it for pip-compile
https://github.com/astral-sh/uv/issues/1624

ci: use `uv`

---

.github/workflows/ci.yaml
imaginairy/config.py
imaginairy/weight_management/execution_trace.py
imaginairy/weight_management/generate_weight_info.py
scripts/controlnet_convert.py

Fixes #488.
See also https://huggingface.co/posts/dn6/357701279407928

fix: update sd15 weight links

---

.github/workflows/ci.yaml
docs/docs/Python/upscale.md
imaginairy/api/generate.py
imaginairy/api/generate_flux.py
imaginairy/cli/clickshell_mod.py
imaginairy/config.py
imaginairy/enhancers/video_interpolation/rife/interpolate.py
imaginairy/img_processors/control_modes.py
imaginairy/modules/diffusion/model.py
imaginairy/modules/sgm/autoencoding/lpips/model/model.py
imaginairy/modules/sgm/diffusionmodules/model.py
imaginairy/schema.py
imaginairy/utils/animations.py
imaginairy/weight_management/conversion.py
requirements-dev.txt
setup.py
tests/conftest.py
tests/img_processors/test_control_modes.py
tests/test_enhancers/test_upscale.py
tests/test_http_app/test_app.py
tests/test_http_app/test_routes.py
tests/test_modules/test_autoencoders.py
tests/test_utils/test_memory_tracker.py
tests/test_utils/test_model_cache.py

Should work on nvidia GPUs with sufficient memory.  Only tested on a 4090.
`imagine "{_landscape-type_|_fruit_|_flower_}. {_style_}"  --model flux --size FHD --upscale -r 20`
5 step image takes 12 seconds to generate at 1920x1080.
Automatically quantizes and caches weights.  Thanks to https://gist.github.com/AmericanPresidentJimmyCarter/873985638e1f3541ba8b00137e7dacd9 for showing how to do it.
Not supported:
- specifying weights
- loras, controlnets
- negative prompts
- image inputs, inpainting
- probably other things

add a barely working flux model
