- imaginairy/enhancers/face_restoration_codeformer.py
- tests/test_api.py
- tests/test_enhancers.py
thanks to @h4rk8s for discovering and finding a remedy
root cause was a model being instantiated inside
FaceRestoreHelper
> fix: fix memory leak in face enhancer

- imaginairy/api.py
- imaginairy/cmds.py
- imaginairy/schema.py
remove face-fixing from upscaled version
> feature: face-fidelity is now configurable

- imaginairy/api.py
- imaginairy/cmds.py
> feature: allow loading custom model weights at command line

- imaginairy/schema.py
> fix: set fidelity default if None is passed in

- README.md
- imaginairy/api.py
- imaginairy/enhancers/prompt_expansion.py
- imaginairy/safety.py
- imaginairy/schema.py
- tests/test_enhancers.py
- tests/test_safety.py
- provides more informative logs
- provides a detailed safety score object
- adds non-bypassable filter for extreme content
> improved safety filter

- Makefile
- README.md
- imaginairy/api.py
- imaginairy/log_utils.py
- imaginairy/modules/diffusion/ddpm.py
- imaginairy/samplers/base.py
- imaginairy/samplers/ddim.py
- imaginairy/samplers/kdiff.py
- imaginairy/samplers/plms.py
- imaginairy/vendored/k_diffusion/sampling.py
- tests/samplers/test_base.py
As documented here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4558#issuecomment-1310387114
- make image logs more consistent
- note which step the progress images belong to in the filename
> mps ksampler fix

- imaginairy/utils.py
autocast not supported on CPU
https://github.com/pytorch/pytorch/issues/55374
https://github.com/invoke-ai/InvokeAI/pull/518
> fix: cpu generation doesn't use autocast

- README.md
- imaginairy/configs/stable-diffusion-v2-inference-v.yaml
- imaginairy/configs/stable-diffusion-v2-inference.yaml
- imaginairy/configs/stable-diffusion-v2-inpainting-inference.yaml
- imaginairy/configs/stable-diffusion-v2-midas-inference.yaml
- imaginairy/configs/stable-diffusion-x4-upscaling.yaml
- imaginairy/model_manager.py
- imaginairy/modules/attention.py
- imaginairy/modules/autoencoder.py
- imaginairy/modules/diffusion/ddpm.py
- imaginairy/modules/diffusion/model.py
- imaginairy/modules/diffusion/openaimodel.py
- imaginairy/modules/diffusion/util.py
- imaginairy/modules/ema.py
- imaginairy/modules/encoders.py
- imaginairy/samplers/ddim.py
- setup.py
working: CUDA and MacOS
working: 512p model with all samplers
working: inpainting with all samplers
working: 768p model with ddim sampler
todo: add new upscaler and depth models
todo: fix lints
todo: fix tests
todo: fix samplers for 768p model
todo: auto-adjust sizes based on model
> feature: Stable Diffusion 2.0

- README.md
- imaginairy/schema.py
> fix: version metadata was broken

- imaginairy/api.py
- imaginairy/enhancers/face_restoration_codeformer.py
- imaginairy/train.py
> feature: run face enhancement on the GPU

- .gitignore
- README.md
- imaginairy/__init__.py
- imaginairy/cmds.py
- imaginairy/model_manager.py
- imaginairy/version.py
- tests/test_model_manager.py
- tests/test_outpaint.py
- tox.ini
- fix: default config wasn't being selected for custom models
> feature: print version

- Makefile
- imaginairy/enhancers/clip_masking.py
- imaginairy/enhancers/describe_image_blip.py
- imaginairy/enhancers/describe_image_clip.py
- imaginairy/enhancers/face_restoration_codeformer.py
- imaginairy/enhancers/prompt_expansion.py
- imaginairy/enhancers/upscale_realesrgan.py
- imaginairy/safety.py
- imaginairy/utils.py
- imaginairy/vendored/clip/simple_tokenizer.py
- requirements-dev.txt
- disable lint fixer that updates to newer syntax
> fix: use py3.7 compat lru_cache

- imaginairy/modules/attention.py
per
- https://github.com/brycedrennan/imaginAIry/issues/175
- https://github.com/invoke-ai/InvokeAI/issues/1244
> fix: MacOS MPS background can't handle large slices

- README.md
- imaginairy/cmds.py
- imaginairy/img_utils.py
- imaginairy/modules/diffusion/openaimodel.py
- imaginairy/outpaint.py
from https://github.com/CompVis/stable-diffusion/issues/60#issuecomment-1240294667
> feature: image sizes can now be multiples of 8 instead of 64

- .gitignore
- README.md
- imaginairy/api.py
- imaginairy/modules/diffusion/ddpm.py
- scripts/asses_memory_usage.py
- tile mode made more efficient. especially when not being used
- unload parts of model if needed
- add script to iteratively make bigger images to test memory
> performance: memory management improvements

- README.md
- docs/examples/immortal_pearl_earring.py
- imaginairy/api.py
- imaginairy/cmds.py
- imaginairy/modules/midas/utils.py
- requirements-dev.txt
- setup.py
> features and refactors

- .github/workflows/ci.yaml
- Makefile
- README.md
- imaginairy/cli/describe.py
- imaginairy/cli/shared.py
- imaginairy/enhancers/face_restoration_codeformer.py
- imaginairy/enhancers/prompt_expansion.py
- imaginairy/feather_tile.py
- imaginairy/img_processors/openpose.py
- imaginairy/model_manager.py
- imaginairy/modules/autoencoder.py
- imaginairy/modules/cldm.py
- imaginairy/modules/diffusion/ddpm.py
- imaginairy/modules/midas/midas/dpt_depth.py
- imaginairy/train.py
- imaginairy/utils.py
- imaginairy/vendored/blip/blip.py
- imaginairy/vendored/blip/blip_itm.py
- imaginairy/vendored/blip/blip_nlvr.py
- imaginairy/vendored/blip/blip_vqa.py
- imaginairy/vendored/blip/med.py
- imaginairy/vendored/blip/nlvr_encoder.py
- imaginairy/vendored/clipseg/__init__.py
- requirements-dev.txt
- scripts/controlnet_convert.py
- setup.py
- tests/conftest.py
by [library change in transformers 4.27.0](https://github.com/huggingface/transformers/commit/8f3b4a1d5bd97045541c43179efe8cd9c58adb76)
> fix: fix model downloads that were broken

- imaginairy/enhancers/describe_image_blip.py
Tested on M1 Macbook Pro.
Fixes issue #302
**Before**
**After**
Needs testing on other platforms to ensure it doesn't break things for other users before merging
> Changed sample to True to generate caption using blip model

- Makefile
- imaginairy/img_processors/control_modes.py
- imaginairy/vendored/imaginairy_normal_map/decoder.py
- imaginairy/vendored/imaginairy_normal_map/encoder.py
- imaginairy/vendored/imaginairy_normal_map/model.py
- imaginairy/vendored/imaginairy_normal_map/submodules.py
- imaginairy/vendored/imaginairy_normal_map/utils.py
- requirements-dev.txt
- setup.py
Fixes conda package. Fixes #317
> fix: move normal map code inline

- imaginairy/api/generate_refiners.py
- imaginairy/enhancers/upscale_realesrgan.py
- imaginairy/utils/model_manager.py
- imaginairy/vendored/realesrgan.py
- imaginairy/weight_management/translation.py
add warning for corrupt weights files
> perf: improve memory usage

- imaginairy/api/video_sample.py
- imaginairy/enhancers/video_interpolation/rife/IFNet_HDv3.py
- imaginairy/enhancers/video_interpolation/rife/RIFE_HDv3.py
- imaginairy/enhancers/video_interpolation/rife/interpolate.py
- imaginairy/enhancers/video_interpolation/rife/msssim.py
- imaginairy/enhancers/video_interpolation/rife/warplayer.py
- imaginairy/utils/animations.py
- uses rife algorithm to interpolate frames
> feature: video interpolation

- README.md
- docs/todo.md
- imaginairy/api/video_sample.py
- imaginairy/enhancers/describe_image_blip.py
- imaginairy/enhancers/face_restoration_codeformer.py
- imaginairy/enhancers/upscale_realesrgan.py
- imaginairy/enhancers/upscale_riverwing.py
- imaginairy/enhancers/video_interpolation/rife/interpolate.py
- imaginairy/img_processors/hed_boundary.py
- imaginairy/img_processors/openpose.py
- imaginairy/modules/midas/midas/base_model.py
- imaginairy/utils/downloads.py
- imaginairy/utils/model_manager.py
- imaginairy/vendored/realesrgan.py
- imaginairy/weight_management/generate_weight_info.py
- scripts/controlnet_convert.py
- tests/test_utils/test_model_manager.py
> refactor: move download related functions to separate module
